version: '3'
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    ports:
      - "1935:1935" # RTMP port
      - "80:80"     # HTTP port
      - "443:443"   # HTTPS port
    volumes:
      - ./data:/data # Persistent data for Let's Encrypt
    environment:
      - STREAM_KEY=your_stream_key_here # Change this to your desired stream key

  certbot:
    image: certbot/certbot
    volumes:
      - ./data:/etc/letsencrypt
    command: certonly --standalone --agree-tos --non-interactive --email alex.conover@salesforce.com -d conoverlabs.cloud
