version: '3'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "80:80"      # HTTP port
      - "443:443"    # HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./hls:/tmp/hls

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot -d yourdomain.com -d www.yourdomain.com

  auth-service:
    build:
      context: ./auth-service  # Path to your Python authentication service code
    ports:
      - "80:80"  # Expose the authentication service on port 80

volumes:
  certs:
  hls:
