version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
      - "443:8443"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
      - ./keys:/etc/letsencrypt/live/conoverlabs.cloud/

  auth:
    build: ./auth
    container_name: auth_server