version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
      - "443:8443"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
      - ./certbot:/tmp/ssl # Share the volume with your Certbot container
      - ./www:/www
    depends_on:
      - certbot

  auth:
    build: ./auth
    container_name: auth_server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/tmp/ssl # Share the volume with your Nginx container
      - ./www:/www
    depends_on:
      - rtmp
    command: certonly --webroot -w /www --agree-tos --email alex.conover@outlook.com -d conoverlabs.cloud
