version: '3'

services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"  # RTMP port
      - "80:80"      # HTTP port
      - "443:443"    # HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/tmp/hls
      # - ./certs:/etc/letsencrypt

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #   command: certonly --standalone --email alex.conover@outlook.com --agree-tos --no-eff-email -d conoverlabs.cloud
  
  auth-service:
    build:
      context: ./auth-service  # Path to your Python authentication service code
    ports:
      - "8181:8181"  # Expose the authentication service on port 8181

volumes:
  hls:
  # certs:

