version: "3.4"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
      - "443:8443"
    container_name: rtmp_server
    volumes:
      - ./data/hls:/tmp/hls
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot

  auth:
    build: ./auth
    container_name: auth_server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"