version: "3.4"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "80:8080"
      - "443:8443"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
      - ./certbot/conf:/ect/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - certbot

  auth:
    build: ./auth
    container_name: auth_server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/ect/nginx/ssl
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --agree-tos --email alex.conover@outlook.com -d conoverlabs.cloud
